keys:
  - &admin age1v492u0esm92zy34e33xd9m7z4jt3v03j233ar75k5m7s0rlxes0sxadr2t
  - &oneohm age1mazttzsgw0eqp5c4mmkm75v07wu7nl07gt0z64qgwe2yzdk8jueq0yys3l

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *admin
          - *oneohm
